//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_questao_tb_atividade1", "tb_atividade", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_atividade), "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_questao), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_questao_tb_tecnologia1", "tb_tecnologia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_tecnologia), "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_questao), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_resposta_tb_questao1", "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_questao), "tb_resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_resposta), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_resultado_tb_resposta1", "tb_resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_resposta), "tb_resultado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_resultado), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "tb_questao_restricoes", "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_questao), "tb_restricao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_restricao))]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_usuario), "tb_ativar_perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_ativar_perfil), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_matricula_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_usuario), "tb_matricula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_matricula), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_resposta_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_usuario), "tb_resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_resposta), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_atividade_tb_turma1", "tb_turma", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_turma), "tb_atividade", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_atividade), true)]
[assembly: EdmRelationshipAttribute("sqlescolaModel", "fk_tb_matricula_tb_turma1", "tb_turma", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SQLEscola.Banco.tb_turma), "tb_matricula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SQLEscola.Banco.tb_matricula), true)]

#endregion

namespace SQLEscola.Banco
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sqlescolaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sqlescolaEntities object using the connection string found in the 'sqlescolaEntities' section of the application configuration file.
        /// </summary>
        public sqlescolaEntities() : base("name=sqlescolaEntities", "sqlescolaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sqlescolaEntities object.
        /// </summary>
        public sqlescolaEntities(string connectionString) : base(connectionString, "sqlescolaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sqlescolaEntities object.
        /// </summary>
        public sqlescolaEntities(EntityConnection connection) : base(connection, "sqlescolaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_ativar_perfil> tb_ativar_perfil
        {
            get
            {
                if ((_tb_ativar_perfil == null))
                {
                    _tb_ativar_perfil = base.CreateObjectSet<tb_ativar_perfil>("tb_ativar_perfil");
                }
                return _tb_ativar_perfil;
            }
        }
        private ObjectSet<tb_ativar_perfil> _tb_ativar_perfil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_atividade> tb_atividade
        {
            get
            {
                if ((_tb_atividade == null))
                {
                    _tb_atividade = base.CreateObjectSet<tb_atividade>("tb_atividade");
                }
                return _tb_atividade;
            }
        }
        private ObjectSet<tb_atividade> _tb_atividade;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_matricula> tb_matricula
        {
            get
            {
                if ((_tb_matricula == null))
                {
                    _tb_matricula = base.CreateObjectSet<tb_matricula>("tb_matricula");
                }
                return _tb_matricula;
            }
        }
        private ObjectSet<tb_matricula> _tb_matricula;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_questao> tb_questao
        {
            get
            {
                if ((_tb_questao == null))
                {
                    _tb_questao = base.CreateObjectSet<tb_questao>("tb_questao");
                }
                return _tb_questao;
            }
        }
        private ObjectSet<tb_questao> _tb_questao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_resposta> tb_resposta
        {
            get
            {
                if ((_tb_resposta == null))
                {
                    _tb_resposta = base.CreateObjectSet<tb_resposta>("tb_resposta");
                }
                return _tb_resposta;
            }
        }
        private ObjectSet<tb_resposta> _tb_resposta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_restricao> tb_restricao
        {
            get
            {
                if ((_tb_restricao == null))
                {
                    _tb_restricao = base.CreateObjectSet<tb_restricao>("tb_restricao");
                }
                return _tb_restricao;
            }
        }
        private ObjectSet<tb_restricao> _tb_restricao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_resultado> tb_resultado
        {
            get
            {
                if ((_tb_resultado == null))
                {
                    _tb_resultado = base.CreateObjectSet<tb_resultado>("tb_resultado");
                }
                return _tb_resultado;
            }
        }
        private ObjectSet<tb_resultado> _tb_resultado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_tecnologia> tb_tecnologia
        {
            get
            {
                if ((_tb_tecnologia == null))
                {
                    _tb_tecnologia = base.CreateObjectSet<tb_tecnologia>("tb_tecnologia");
                }
                return _tb_tecnologia;
            }
        }
        private ObjectSet<tb_tecnologia> _tb_tecnologia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_usuario> tb_usuario
        {
            get
            {
                if ((_tb_usuario == null))
                {
                    _tb_usuario = base.CreateObjectSet<tb_usuario>("tb_usuario");
                }
                return _tb_usuario;
            }
        }
        private ObjectSet<tb_usuario> _tb_usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_turma> tb_turma
        {
            get
            {
                if ((_tb_turma == null))
                {
                    _tb_turma = base.CreateObjectSet<tb_turma>("tb_turma");
                }
                return _tb_turma;
            }
        }
        private ObjectSet<tb_turma> _tb_turma;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_ativar_perfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_ativar_perfil(tb_ativar_perfil tb_ativar_perfil)
        {
            base.AddObject("tb_ativar_perfil", tb_ativar_perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_atividade EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_atividade(tb_atividade tb_atividade)
        {
            base.AddObject("tb_atividade", tb_atividade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_matricula EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_matricula(tb_matricula tb_matricula)
        {
            base.AddObject("tb_matricula", tb_matricula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_questao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_questao(tb_questao tb_questao)
        {
            base.AddObject("tb_questao", tb_questao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_resposta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_resposta(tb_resposta tb_resposta)
        {
            base.AddObject("tb_resposta", tb_resposta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_restricao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_restricao(tb_restricao tb_restricao)
        {
            base.AddObject("tb_restricao", tb_restricao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_resultado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_resultado(tb_resultado tb_resultado)
        {
            base.AddObject("tb_resultado", tb_resultado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_tecnologia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_tecnologia(tb_tecnologia tb_tecnologia)
        {
            base.AddObject("tb_tecnologia", tb_tecnologia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_usuario(tb_usuario tb_usuario)
        {
            base.AddObject("tb_usuario", tb_usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_turma EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_turma(tb_turma tb_turma)
        {
            base.AddObject("tb_turma", tb_turma);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_ativar_perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_ativar_perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_ativar_perfil object.
        /// </summary>
        /// <param name="id_Ativar_Perfil">Initial value of the Id_Ativar_Perfil property.</param>
        /// <param name="id_Usuario">Initial value of the Id_Usuario property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static tb_ativar_perfil Createtb_ativar_perfil(global::System.Int32 id_Ativar_Perfil, global::System.Int32 id_Usuario, global::System.String status)
        {
            tb_ativar_perfil tb_ativar_perfil = new tb_ativar_perfil();
            tb_ativar_perfil.Id_Ativar_Perfil = id_Ativar_Perfil;
            tb_ativar_perfil.Id_Usuario = id_Usuario;
            tb_ativar_perfil.Status = status;
            return tb_ativar_perfil;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Ativar_Perfil
        {
            get
            {
                return _Id_Ativar_Perfil;
            }
            set
            {
                if (_Id_Ativar_Perfil != value)
                {
                    OnId_Ativar_PerfilChanging(value);
                    ReportPropertyChanging("Id_Ativar_Perfil");
                    _Id_Ativar_Perfil = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Ativar_Perfil");
                    OnId_Ativar_PerfilChanged();
                }
            }
        }
        private global::System.Int32 _Id_Ativar_Perfil;
        partial void OnId_Ativar_PerfilChanging(global::System.Int32 value);
        partial void OnId_Ativar_PerfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Usuario
        {
            get
            {
                return _Id_Usuario;
            }
            set
            {
                OnId_UsuarioChanging(value);
                ReportPropertyChanging("Id_Usuario");
                _Id_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Usuario");
                OnId_UsuarioChanged();
            }
        }
        private global::System.Int32 _Id_Usuario;
        partial void OnId_UsuarioChanging(global::System.Int32 value);
        partial void OnId_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_atividade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_atividade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_atividade object.
        /// </summary>
        /// <param name="id_Atividade">Initial value of the Id_Atividade property.</param>
        /// <param name="id_Turma">Initial value of the Id_Turma property.</param>
        /// <param name="nome_Atividade">Initial value of the Nome_Atividade property.</param>
        public static tb_atividade Createtb_atividade(global::System.Int32 id_Atividade, global::System.Int32 id_Turma, global::System.String nome_Atividade)
        {
            tb_atividade tb_atividade = new tb_atividade();
            tb_atividade.Id_Atividade = id_Atividade;
            tb_atividade.Id_Turma = id_Turma;
            tb_atividade.Nome_Atividade = nome_Atividade;
            return tb_atividade;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Atividade
        {
            get
            {
                return _Id_Atividade;
            }
            set
            {
                if (_Id_Atividade != value)
                {
                    OnId_AtividadeChanging(value);
                    ReportPropertyChanging("Id_Atividade");
                    _Id_Atividade = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Atividade");
                    OnId_AtividadeChanged();
                }
            }
        }
        private global::System.Int32 _Id_Atividade;
        partial void OnId_AtividadeChanging(global::System.Int32 value);
        partial void OnId_AtividadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Turma
        {
            get
            {
                return _Id_Turma;
            }
            set
            {
                OnId_TurmaChanging(value);
                ReportPropertyChanging("Id_Turma");
                _Id_Turma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Turma");
                OnId_TurmaChanged();
            }
        }
        private global::System.Int32 _Id_Turma;
        partial void OnId_TurmaChanging(global::System.Int32 value);
        partial void OnId_TurmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome_Atividade
        {
            get
            {
                return _Nome_Atividade;
            }
            set
            {
                OnNome_AtividadeChanging(value);
                ReportPropertyChanging("Nome_Atividade");
                _Nome_Atividade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome_Atividade");
                OnNome_AtividadeChanged();
            }
        }
        private global::System.String _Nome_Atividade;
        partial void OnNome_AtividadeChanging(global::System.String value);
        partial void OnNome_AtividadeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_questao_tb_atividade1", "tb_questao")]
        public EntityCollection<tb_questao> tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_questao>("sqlescolaModel.fk_tb_questao_tb_atividade1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_questao>("sqlescolaModel.fk_tb_questao_tb_atividade1", "tb_questao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_atividade_tb_turma1", "tb_turma")]
        public tb_turma tb_turma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_turma>("sqlescolaModel.fk_tb_atividade_tb_turma1", "tb_turma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_turma>("sqlescolaModel.fk_tb_atividade_tb_turma1", "tb_turma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_turma> tb_turmaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_turma>("sqlescolaModel.fk_tb_atividade_tb_turma1", "tb_turma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_turma>("sqlescolaModel.fk_tb_atividade_tb_turma1", "tb_turma", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_matricula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_matricula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_matricula object.
        /// </summary>
        /// <param name="id_Matricula">Initial value of the Id_Matricula property.</param>
        /// <param name="id_Usuario">Initial value of the Id_Usuario property.</param>
        /// <param name="id_Turma">Initial value of the Id_Turma property.</param>
        public static tb_matricula Createtb_matricula(global::System.Int32 id_Matricula, global::System.Int32 id_Usuario, global::System.Int32 id_Turma)
        {
            tb_matricula tb_matricula = new tb_matricula();
            tb_matricula.Id_Matricula = id_Matricula;
            tb_matricula.Id_Usuario = id_Usuario;
            tb_matricula.Id_Turma = id_Turma;
            return tb_matricula;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Matricula
        {
            get
            {
                return _Id_Matricula;
            }
            set
            {
                if (_Id_Matricula != value)
                {
                    OnId_MatriculaChanging(value);
                    ReportPropertyChanging("Id_Matricula");
                    _Id_Matricula = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Matricula");
                    OnId_MatriculaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Matricula;
        partial void OnId_MatriculaChanging(global::System.Int32 value);
        partial void OnId_MatriculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Usuario
        {
            get
            {
                return _Id_Usuario;
            }
            set
            {
                OnId_UsuarioChanging(value);
                ReportPropertyChanging("Id_Usuario");
                _Id_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Usuario");
                OnId_UsuarioChanged();
            }
        }
        private global::System.Int32 _Id_Usuario;
        partial void OnId_UsuarioChanging(global::System.Int32 value);
        partial void OnId_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Turma
        {
            get
            {
                return _Id_Turma;
            }
            set
            {
                OnId_TurmaChanging(value);
                ReportPropertyChanging("Id_Turma");
                _Id_Turma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Turma");
                OnId_TurmaChanged();
            }
        }
        private global::System.Int32 _Id_Turma;
        partial void OnId_TurmaChanging(global::System.Int32 value);
        partial void OnId_TurmaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_matricula_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_matricula_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_matricula_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_matricula_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_matricula_tb_usuario1", "tb_usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_matricula_tb_turma1", "tb_turma")]
        public tb_turma tb_turma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_turma>("sqlescolaModel.fk_tb_matricula_tb_turma1", "tb_turma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_turma>("sqlescolaModel.fk_tb_matricula_tb_turma1", "tb_turma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_turma> tb_turmaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_turma>("sqlescolaModel.fk_tb_matricula_tb_turma1", "tb_turma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_turma>("sqlescolaModel.fk_tb_matricula_tb_turma1", "tb_turma", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_questao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_questao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_questao object.
        /// </summary>
        /// <param name="id_Questao">Initial value of the Id_Questao property.</param>
        /// <param name="id_Tecnologia">Initial value of the Id_Tecnologia property.</param>
        /// <param name="id_Atividade">Initial value of the Id_Atividade property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="scriptCriacao">Initial value of the ScriptCriacao property.</param>
        /// <param name="scriptPovoamento">Initial value of the ScriptPovoamento property.</param>
        /// <param name="scriptResolucao">Initial value of the ScriptResolucao property.</param>
        /// <param name="ordem">Initial value of the Ordem property.</param>
        public static tb_questao Createtb_questao(global::System.Int32 id_Questao, global::System.Int32 id_Tecnologia, global::System.Int32 id_Atividade, global::System.String descricao, global::System.String scriptCriacao, global::System.String scriptPovoamento, global::System.String scriptResolucao, global::System.Int32 ordem)
        {
            tb_questao tb_questao = new tb_questao();
            tb_questao.Id_Questao = id_Questao;
            tb_questao.Id_Tecnologia = id_Tecnologia;
            tb_questao.Id_Atividade = id_Atividade;
            tb_questao.Descricao = descricao;
            tb_questao.ScriptCriacao = scriptCriacao;
            tb_questao.ScriptPovoamento = scriptPovoamento;
            tb_questao.ScriptResolucao = scriptResolucao;
            tb_questao.Ordem = ordem;
            return tb_questao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Questao
        {
            get
            {
                return _Id_Questao;
            }
            set
            {
                if (_Id_Questao != value)
                {
                    OnId_QuestaoChanging(value);
                    ReportPropertyChanging("Id_Questao");
                    _Id_Questao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Questao");
                    OnId_QuestaoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Questao;
        partial void OnId_QuestaoChanging(global::System.Int32 value);
        partial void OnId_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Tecnologia
        {
            get
            {
                return _Id_Tecnologia;
            }
            set
            {
                OnId_TecnologiaChanging(value);
                ReportPropertyChanging("Id_Tecnologia");
                _Id_Tecnologia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Tecnologia");
                OnId_TecnologiaChanged();
            }
        }
        private global::System.Int32 _Id_Tecnologia;
        partial void OnId_TecnologiaChanging(global::System.Int32 value);
        partial void OnId_TecnologiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Atividade
        {
            get
            {
                return _Id_Atividade;
            }
            set
            {
                OnId_AtividadeChanging(value);
                ReportPropertyChanging("Id_Atividade");
                _Id_Atividade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Atividade");
                OnId_AtividadeChanged();
            }
        }
        private global::System.Int32 _Id_Atividade;
        partial void OnId_AtividadeChanging(global::System.Int32 value);
        partial void OnId_AtividadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScriptCriacao
        {
            get
            {
                return _ScriptCriacao;
            }
            set
            {
                OnScriptCriacaoChanging(value);
                ReportPropertyChanging("ScriptCriacao");
                _ScriptCriacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScriptCriacao");
                OnScriptCriacaoChanged();
            }
        }
        private global::System.String _ScriptCriacao;
        partial void OnScriptCriacaoChanging(global::System.String value);
        partial void OnScriptCriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScriptPovoamento
        {
            get
            {
                return _ScriptPovoamento;
            }
            set
            {
                OnScriptPovoamentoChanging(value);
                ReportPropertyChanging("ScriptPovoamento");
                _ScriptPovoamento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScriptPovoamento");
                OnScriptPovoamentoChanged();
            }
        }
        private global::System.String _ScriptPovoamento;
        partial void OnScriptPovoamentoChanging(global::System.String value);
        partial void OnScriptPovoamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScriptResolucao
        {
            get
            {
                return _ScriptResolucao;
            }
            set
            {
                OnScriptResolucaoChanging(value);
                ReportPropertyChanging("ScriptResolucao");
                _ScriptResolucao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScriptResolucao");
                OnScriptResolucaoChanged();
            }
        }
        private global::System.String _ScriptResolucao;
        partial void OnScriptResolucaoChanging(global::System.String value);
        partial void OnScriptResolucaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ordem
        {
            get
            {
                return _Ordem;
            }
            set
            {
                OnOrdemChanging(value);
                ReportPropertyChanging("Ordem");
                _Ordem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ordem");
                OnOrdemChanged();
            }
        }
        private global::System.Int32 _Ordem;
        partial void OnOrdemChanging(global::System.Int32 value);
        partial void OnOrdemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data_Criacao
        {
            get
            {
                return _Data_Criacao;
            }
            set
            {
                OnData_CriacaoChanging(value);
                ReportPropertyChanging("Data_Criacao");
                _Data_Criacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_Criacao");
                OnData_CriacaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data_Criacao;
        partial void OnData_CriacaoChanging(Nullable<global::System.DateTime> value);
        partial void OnData_CriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data_Alteracao
        {
            get
            {
                return _Data_Alteracao;
            }
            set
            {
                OnData_AlteracaoChanging(value);
                ReportPropertyChanging("Data_Alteracao");
                _Data_Alteracao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_Alteracao");
                OnData_AlteracaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data_Alteracao;
        partial void OnData_AlteracaoChanging(Nullable<global::System.DateTime> value);
        partial void OnData_AlteracaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_questao_tb_atividade1", "tb_atividade")]
        public tb_atividade tb_atividade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_atividade>("sqlescolaModel.fk_tb_questao_tb_atividade1", "tb_atividade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_atividade>("sqlescolaModel.fk_tb_questao_tb_atividade1", "tb_atividade").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_atividade> tb_atividadeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_atividade>("sqlescolaModel.fk_tb_questao_tb_atividade1", "tb_atividade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_atividade>("sqlescolaModel.fk_tb_questao_tb_atividade1", "tb_atividade", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_questao_tb_tecnologia1", "tb_tecnologia")]
        public tb_tecnologia tb_tecnologia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_tecnologia>("sqlescolaModel.fk_tb_questao_tb_tecnologia1", "tb_tecnologia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_tecnologia>("sqlescolaModel.fk_tb_questao_tb_tecnologia1", "tb_tecnologia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_tecnologia> tb_tecnologiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_tecnologia>("sqlescolaModel.fk_tb_questao_tb_tecnologia1", "tb_tecnologia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_tecnologia>("sqlescolaModel.fk_tb_questao_tb_tecnologia1", "tb_tecnologia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_resposta_tb_questao1", "tb_resposta")]
        public EntityCollection<tb_resposta> tb_resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_resposta>("sqlescolaModel.fk_tb_resposta_tb_questao1", "tb_resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_resposta>("sqlescolaModel.fk_tb_resposta_tb_questao1", "tb_resposta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "tb_questao_restricoes", "tb_restricao")]
        public EntityCollection<tb_restricao> tb_restricao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_restricao>("sqlescolaModel.tb_questao_restricoes", "tb_restricao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_restricao>("sqlescolaModel.tb_questao_restricoes", "tb_restricao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_resposta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_resposta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_resposta object.
        /// </summary>
        /// <param name="id_Resposta">Initial value of the Id_Resposta property.</param>
        /// <param name="scriptResposta">Initial value of the ScriptResposta property.</param>
        /// <param name="id_Usuario">Initial value of the Id_Usuario property.</param>
        /// <param name="data_Resposta">Initial value of the Data_Resposta property.</param>
        /// <param name="id_Questao">Initial value of the Id_Questao property.</param>
        public static tb_resposta Createtb_resposta(global::System.Int32 id_Resposta, global::System.String scriptResposta, global::System.Int32 id_Usuario, global::System.DateTime data_Resposta, global::System.Int32 id_Questao)
        {
            tb_resposta tb_resposta = new tb_resposta();
            tb_resposta.Id_Resposta = id_Resposta;
            tb_resposta.ScriptResposta = scriptResposta;
            tb_resposta.Id_Usuario = id_Usuario;
            tb_resposta.Data_Resposta = data_Resposta;
            tb_resposta.Id_Questao = id_Questao;
            return tb_resposta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Resposta
        {
            get
            {
                return _Id_Resposta;
            }
            set
            {
                if (_Id_Resposta != value)
                {
                    OnId_RespostaChanging(value);
                    ReportPropertyChanging("Id_Resposta");
                    _Id_Resposta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Resposta");
                    OnId_RespostaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Resposta;
        partial void OnId_RespostaChanging(global::System.Int32 value);
        partial void OnId_RespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScriptResposta
        {
            get
            {
                return _ScriptResposta;
            }
            set
            {
                OnScriptRespostaChanging(value);
                ReportPropertyChanging("ScriptResposta");
                _ScriptResposta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScriptResposta");
                OnScriptRespostaChanged();
            }
        }
        private global::System.String _ScriptResposta;
        partial void OnScriptRespostaChanging(global::System.String value);
        partial void OnScriptRespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Usuario
        {
            get
            {
                return _Id_Usuario;
            }
            set
            {
                OnId_UsuarioChanging(value);
                ReportPropertyChanging("Id_Usuario");
                _Id_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Usuario");
                OnId_UsuarioChanged();
            }
        }
        private global::System.Int32 _Id_Usuario;
        partial void OnId_UsuarioChanging(global::System.Int32 value);
        partial void OnId_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data_Resposta
        {
            get
            {
                return _Data_Resposta;
            }
            set
            {
                OnData_RespostaChanging(value);
                ReportPropertyChanging("Data_Resposta");
                _Data_Resposta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_Resposta");
                OnData_RespostaChanged();
            }
        }
        private global::System.DateTime _Data_Resposta;
        partial void OnData_RespostaChanging(global::System.DateTime value);
        partial void OnData_RespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Questao
        {
            get
            {
                return _Id_Questao;
            }
            set
            {
                OnId_QuestaoChanging(value);
                ReportPropertyChanging("Id_Questao");
                _Id_Questao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Questao");
                OnId_QuestaoChanged();
            }
        }
        private global::System.Int32 _Id_Questao;
        partial void OnId_QuestaoChanging(global::System.Int32 value);
        partial void OnId_QuestaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_resposta_tb_questao1", "tb_questao")]
        public tb_questao tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("sqlescolaModel.fk_tb_resposta_tb_questao1", "tb_questao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("sqlescolaModel.fk_tb_resposta_tb_questao1", "tb_questao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_questao> tb_questaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("sqlescolaModel.fk_tb_resposta_tb_questao1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_questao>("sqlescolaModel.fk_tb_resposta_tb_questao1", "tb_questao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_resultado_tb_resposta1", "tb_resultado")]
        public EntityCollection<tb_resultado> tb_resultado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_resultado>("sqlescolaModel.fk_tb_resultado_tb_resposta1", "tb_resultado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_resultado>("sqlescolaModel.fk_tb_resultado_tb_resposta1", "tb_resultado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_resposta_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_resposta_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_resposta_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_resposta_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("sqlescolaModel.fk_tb_resposta_tb_usuario1", "tb_usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_restricao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_restricao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_restricao object.
        /// </summary>
        /// <param name="id_Restricoes">Initial value of the Id_Restricoes property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="valores">Initial value of the Valores property.</param>
        public static tb_restricao Createtb_restricao(global::System.Int32 id_Restricoes, global::System.String descricao, global::System.Double valores)
        {
            tb_restricao tb_restricao = new tb_restricao();
            tb_restricao.Id_Restricoes = id_Restricoes;
            tb_restricao.Descricao = descricao;
            tb_restricao.Valores = valores;
            return tb_restricao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Restricoes
        {
            get
            {
                return _Id_Restricoes;
            }
            set
            {
                if (_Id_Restricoes != value)
                {
                    OnId_RestricoesChanging(value);
                    ReportPropertyChanging("Id_Restricoes");
                    _Id_Restricoes = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Restricoes");
                    OnId_RestricoesChanged();
                }
            }
        }
        private global::System.Int32 _Id_Restricoes;
        partial void OnId_RestricoesChanging(global::System.Int32 value);
        partial void OnId_RestricoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Valores
        {
            get
            {
                return _Valores;
            }
            set
            {
                OnValoresChanging(value);
                ReportPropertyChanging("Valores");
                _Valores = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valores");
                OnValoresChanged();
            }
        }
        private global::System.Double _Valores;
        partial void OnValoresChanging(global::System.Double value);
        partial void OnValoresChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "tb_questao_restricoes", "tb_questao")]
        public EntityCollection<tb_questao> tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_questao>("sqlescolaModel.tb_questao_restricoes", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_questao>("sqlescolaModel.tb_questao_restricoes", "tb_questao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_resultado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_resultado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_resultado object.
        /// </summary>
        /// <param name="id_Resultado">Initial value of the Id_Resultado property.</param>
        /// <param name="id_Resposta">Initial value of the Id_Resposta property.</param>
        public static tb_resultado Createtb_resultado(global::System.Int32 id_Resultado, global::System.Int32 id_Resposta)
        {
            tb_resultado tb_resultado = new tb_resultado();
            tb_resultado.Id_Resultado = id_Resultado;
            tb_resultado.Id_Resposta = id_Resposta;
            return tb_resultado;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Resultado
        {
            get
            {
                return _Id_Resultado;
            }
            set
            {
                if (_Id_Resultado != value)
                {
                    OnId_ResultadoChanging(value);
                    ReportPropertyChanging("Id_Resultado");
                    _Id_Resultado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Resultado");
                    OnId_ResultadoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Resultado;
        partial void OnId_ResultadoChanging(global::System.Int32 value);
        partial void OnId_ResultadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Erros
        {
            get
            {
                return _Erros;
            }
            set
            {
                OnErrosChanging(value);
                ReportPropertyChanging("Erros");
                _Erros = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Erros");
                OnErrosChanged();
            }
        }
        private global::System.String _Erros;
        partial void OnErrosChanging(global::System.String value);
        partial void OnErrosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentarios_Prof
        {
            get
            {
                return _Comentarios_Prof;
            }
            set
            {
                OnComentarios_ProfChanging(value);
                ReportPropertyChanging("Comentarios_Prof");
                _Comentarios_Prof = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentarios_Prof");
                OnComentarios_ProfChanged();
            }
        }
        private global::System.String _Comentarios_Prof;
        partial void OnComentarios_ProfChanging(global::System.String value);
        partial void OnComentarios_ProfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Resposta
        {
            get
            {
                return _Id_Resposta;
            }
            set
            {
                OnId_RespostaChanging(value);
                ReportPropertyChanging("Id_Resposta");
                _Id_Resposta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Resposta");
                OnId_RespostaChanged();
            }
        }
        private global::System.Int32 _Id_Resposta;
        partial void OnId_RespostaChanging(global::System.Int32 value);
        partial void OnId_RespostaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_resultado_tb_resposta1", "tb_resposta")]
        public tb_resposta tb_resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_resposta>("sqlescolaModel.fk_tb_resultado_tb_resposta1", "tb_resposta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_resposta>("sqlescolaModel.fk_tb_resultado_tb_resposta1", "tb_resposta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_resposta> tb_respostaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_resposta>("sqlescolaModel.fk_tb_resultado_tb_resposta1", "tb_resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_resposta>("sqlescolaModel.fk_tb_resultado_tb_resposta1", "tb_resposta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_tecnologia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_tecnologia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_tecnologia object.
        /// </summary>
        /// <param name="id_Tecnologia">Initial value of the Id_Tecnologia property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static tb_tecnologia Createtb_tecnologia(global::System.Int32 id_Tecnologia, global::System.String descricao)
        {
            tb_tecnologia tb_tecnologia = new tb_tecnologia();
            tb_tecnologia.Id_Tecnologia = id_Tecnologia;
            tb_tecnologia.Descricao = descricao;
            return tb_tecnologia;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Tecnologia
        {
            get
            {
                return _Id_Tecnologia;
            }
            set
            {
                if (_Id_Tecnologia != value)
                {
                    OnId_TecnologiaChanging(value);
                    ReportPropertyChanging("Id_Tecnologia");
                    _Id_Tecnologia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Tecnologia");
                    OnId_TecnologiaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Tecnologia;
        partial void OnId_TecnologiaChanging(global::System.Int32 value);
        partial void OnId_TecnologiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Versao
        {
            get
            {
                return _Versao;
            }
            set
            {
                OnVersaoChanging(value);
                ReportPropertyChanging("Versao");
                _Versao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Versao");
                OnVersaoChanged();
            }
        }
        private global::System.String _Versao;
        partial void OnVersaoChanging(global::System.String value);
        partial void OnVersaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_questao_tb_tecnologia1", "tb_questao")]
        public EntityCollection<tb_questao> tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_questao>("sqlescolaModel.fk_tb_questao_tb_tecnologia1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_questao>("sqlescolaModel.fk_tb_questao_tb_tecnologia1", "tb_questao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_turma")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_turma : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_turma object.
        /// </summary>
        /// <param name="id_Turma">Initial value of the Id_Turma property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="id_Usuario">Initial value of the Id_Usuario property.</param>
        public static tb_turma Createtb_turma(global::System.Int32 id_Turma, global::System.String nome, global::System.Int32 id_Usuario)
        {
            tb_turma tb_turma = new tb_turma();
            tb_turma.Id_Turma = id_Turma;
            tb_turma.Nome = nome;
            tb_turma.Id_Usuario = id_Usuario;
            return tb_turma;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Turma
        {
            get
            {
                return _Id_Turma;
            }
            set
            {
                if (_Id_Turma != value)
                {
                    OnId_TurmaChanging(value);
                    ReportPropertyChanging("Id_Turma");
                    _Id_Turma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Turma");
                    OnId_TurmaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Turma;
        partial void OnId_TurmaChanging(global::System.Int32 value);
        partial void OnId_TurmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Usuario
        {
            get
            {
                return _Id_Usuario;
            }
            set
            {
                OnId_UsuarioChanging(value);
                ReportPropertyChanging("Id_Usuario");
                _Id_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Usuario");
                OnId_UsuarioChanged();
            }
        }
        private global::System.Int32 _Id_Usuario;
        partial void OnId_UsuarioChanging(global::System.Int32 value);
        partial void OnId_UsuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_atividade_tb_turma1", "tb_atividade")]
        public EntityCollection<tb_atividade> tb_atividade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_atividade>("sqlescolaModel.fk_tb_atividade_tb_turma1", "tb_atividade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_atividade>("sqlescolaModel.fk_tb_atividade_tb_turma1", "tb_atividade", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_matricula_tb_turma1", "tb_matricula")]
        public EntityCollection<tb_matricula> tb_matricula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_matricula>("sqlescolaModel.fk_tb_matricula_tb_turma1", "tb_matricula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_matricula>("sqlescolaModel.fk_tb_matricula_tb_turma1", "tb_matricula", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sqlescolaModel", Name="tb_usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_usuario object.
        /// </summary>
        /// <param name="id_Usuario">Initial value of the Id_Usuario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static tb_usuario Createtb_usuario(global::System.Int32 id_Usuario, global::System.String nome, global::System.String email)
        {
            tb_usuario tb_usuario = new tb_usuario();
            tb_usuario.Id_Usuario = id_Usuario;
            tb_usuario.Nome = nome;
            tb_usuario.Email = email;
            return tb_usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Usuario
        {
            get
            {
                return _Id_Usuario;
            }
            set
            {
                if (_Id_Usuario != value)
                {
                    OnId_UsuarioChanging(value);
                    ReportPropertyChanging("Id_Usuario");
                    _Id_Usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Usuario");
                    OnId_UsuarioChanged();
                }
            }
        }
        private global::System.Int32 _Id_Usuario;
        partial void OnId_UsuarioChanging(global::System.Int32 value);
        partial void OnId_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Foto
        {
            get
            {
                return StructuralObject.GetValidValue(_Foto);
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.Byte[] _Foto;
        partial void OnFotoChanging(global::System.Byte[] value);
        partial void OnFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_ativar_perfil")]
        public EntityCollection<tb_ativar_perfil> tb_ativar_perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_ativar_perfil>("sqlescolaModel.fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_ativar_perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_ativar_perfil>("sqlescolaModel.fk_tb_usuario_has_tb_turma_tb_usuario1", "tb_ativar_perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_matricula_tb_usuario1", "tb_matricula")]
        public EntityCollection<tb_matricula> tb_matricula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_matricula>("sqlescolaModel.fk_tb_matricula_tb_usuario1", "tb_matricula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_matricula>("sqlescolaModel.fk_tb_matricula_tb_usuario1", "tb_matricula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sqlescolaModel", "fk_tb_resposta_tb_usuario1", "tb_resposta")]
        public EntityCollection<tb_resposta> tb_resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_resposta>("sqlescolaModel.fk_tb_resposta_tb_usuario1", "tb_resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_resposta>("sqlescolaModel.fk_tb_resposta_tb_usuario1", "tb_resposta", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
